---
- name: Create system aliases for all users + secret file
  hosts: localhost
  become: true

  tasks:
    - name: create aliases script in profile.d
      copy:
        dest: /etc/profile.d/aliases.sh
        content: |
          alias d='docker'
          alias dc='docker-compose'

    - name: Create the secret file
      copy:
        dest: /etc/topsecret.txt
        content: |
          t0ps3cr3t 
        owner: root
        group: root
        mode: '0600'